### ISSUE TITLE
Roosevelt-logger cuts off newlines at the end of a line

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt-logger#61]
The Roosevelt logger currently will trim off any whitespace (which includes newlines) at the end of the string that is outputted. This could cause issues if I want to add some newlines to put some spacing in the logs.

This is done at [logger.js line 199](https://github.com/rooseveltframework/roosevelt-logger/blob/master/logger.js#L199)

Should this stay or should we have the option to have extra newlines at the end of a log?

## Example

Say I enter this line to be logged:

```js
logger.log('test\n')
```

So I want to have an extra newline under the line, but with how the logger works currently, it will trim off the `\n` at the end.

**Comment by kethinov** [comment]
I think we should consider this a bug.
