### ISSUE TITLE
Add prefix field for log levels

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/roosevelt-logger#8]
For each log level, allow a prefix field to setup a defined emoji that will be attached in front of each log entry by default. In the case that emojis are disabled, possibly default back to either a defined string or the name of the log level.

**Comment by kethinov** [comment]
What we need is more like a generic prefix feature. Doesn't need to be an emoji, but our defaults will be. We want to be able to customize that prefix to change the emoji or change it to any arbitrary string or disable it altogether. Seems like we need a param for that.
